### ISSUE TITLE
Upgrade @graphprotocol/graph-cli 

### ISSUE THREAD

**Issue by Tim-W** [Open-Attestation/token-registry-subgraph#12]
Hi, regarding the latest discussion at https://github.com/TradeTrust/tradetrust-website/discussions/803 I started investigating the token-registry-subgraph repository to use for querying smart contract data. Looking very useful!

Our current project is built on Ethereum Sepolia, however this network is not yet supported by the current graph-cli version in this repo. Consider upgrading it to the latest version please! 

@superical

**Comment by superical** [comment]
Thanks for raising this! I'll put up a new release with the update tomorrow.🙂

**Comment by superical** [comment]
@Tim-W We have released v1.0.1 which includes an updated version of the CLI that now supports Sepolia. :)
